version: "3.6"
services:
  #PHP Service
  techpump-challenge-php:
    build: docker/php-fpm
    container_name: techpump-challenge-php
    working_dir: /var/www
    volumes:
      - ./var/www:/var/www
      - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - techpump-challenge-network
    user: ${UID}:${GID}

  #Nginx Service
  techpump-challenge-nginx:
    image: nginx:alpine
    container_name: techpump-challenge-nginx
    ports:
      - "8090:80"
    volumes:
      - ./var/www/public:/var/www/public
      - ./logs:/var/log/nginx
      - ./docker/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - techpump-challenge-network

  #MySQL Service
  techpump-challenge-mysql:
    image: mysql:5.7.22
    container_name: techpump-challenge-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=techpumpchallenge
      - MYSQL_USER=techpumpuser
      - MYSQL_PASSWORD=techpump!!Pass
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/conf/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - techpump-challenge-network

#Docker Networks
networks:
  techpump-challenge-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
